---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nifi
  namespace: nifi
  labels:
    app.kubernetes.io/part-of: nifi-system
spec:
  selector:
    matchLabels:
      app: nifi
  serviceName: nifi
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: nifi
        app.kubernetes.io/part-of: nifi-system
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: server
        image: apache/nifi:1.18.0
        ports:
        - containerPort: 8443
        env:
        - name: NIFI_WEB_HTTPS_HOST
          value: localhost
        - name: DEBUG
          value: "true"
        # - name: NIFI_WEB_HTTPS_PORT
        #   value: "8443"
        - name: NIFI_WEB_PROXY_HOST
          value: "localhost:8081,nifi.tap.h2o-2-1249.h2o.vmware.com:443,10.220.65.161:443"
  #       volumeMounts:
  #       - name: nifi
  #         mountPath: /opt/nifi/nifi-current
  # volumeClaimTemplates:
  # - metadata:
  #     name: nifi
  #   spec:
  #     accessModes: [ "ReadWriteOnce" ]
  #     storageClassName: "vc01cl01-t0compute"
  #     resources:
  #       requests:
  #         storage: 1Gi